CREATE TABLE IF NOT EXISTS public_feed_items (
  id TEXT PRIMARY KEY,
  workspace TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'manual',
  source_id TEXT,
  state TEXT NOT NULL,
  title TEXT NOT NULL,
  detail TEXT NOT NULL,
  body TEXT,
  links_json TEXT NOT NULL DEFAULT '[]',
  tone TEXT NOT NULL DEFAULT 'white',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_public INTEGER NOT NULL DEFAULT 1,
  url TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_public_feed_items_workspace_public_sort
  ON public_feed_items (workspace, is_public, sort_order, updated_at);

INSERT INTO public_feed_items (
  id,
  workspace,
  source,
  source_id,
  state,
  title,
  detail,
  body,
  links_json,
  tone,
  sort_order,
  is_public,
  url,
  updated_at
) VALUES
  (
    'BRY-5',
    'brysonbenjamin',
    'linear',
    'BRY-5',
    'Backlog',
    'Linear feed bridge: daily sync + live task log',
    'Wiring a real Linear sync into this panel, plus per-task pages you are looking at right now.',
    'Wiring a real Linear sync into this panel: a daily Render cron job pulls public-feed labeled issues out of Linear and mirrors them here, and each card now opens into a full page with the curated write-up and any attached documentation links.',
    '[]',
    'blue',
    5,
    1,
    NULL,
    '2026-07-18T14:54:21.775Z'
  ),
  (
    'BB-04',
    'brysonbenjamin',
    'manual',
    NULL,
    'Live',
    'Open the public build feed',
    'D1-backed workspace entries are serving through the Pages Function at /api/feed.',
    'D1-backed workspace entries are serving through the Pages Function at /api/feed. The feed panel reads a curated projection of the Linear workspace, refreshed on a daily cron.',
    '[]',
    'mint',
    10,
    1,
    NULL,
    '2026-07-18T12:00:00Z'
  ),
  (
    'BB-03',
    'brysonbenjamin',
    'manual',
    NULL,
    'In motion',
    'Shape the public operating surface',
    'Navigation, archive model, and first durable page primitives.',
    'Navigation, archive model, and first durable page primitives. This covers the routing shell the rest of the site pages will sit inside.',
    '[]',
    'amber',
    20,
    1,
    NULL,
    '2026-07-18T11:00:00Z'
  ),
  (
    'BB-02',
    'brysonbenjamin',
    'manual',
    NULL,
    'Shipped',
    'Bring the construction page online',
    'Cloudflare Pages, apex domain, and early system status.',
    'Cloudflare Pages, apex domain, and early system status. First production deploy of the SPA shell.',
    '[]',
    'white',
    30,
    1,
    NULL,
    '2026-07-18T10:00:00Z'
  ),
  (
    'BB-01',
    'brysonbenjamin',
    'manual',
    NULL,
    'Seeded',
    'Lay the full-stack foundation',
    'Vite, Bun, Hono, Drizzle, Neon, Render, and Cloudflare rails.',
    'Vite, Bun, Hono, Drizzle, Neon, Render, and Cloudflare rails. The base workspace all later work builds on top of.',
    '[]',
    'blue',
    40,
    1,
    NULL,
    '2026-07-18T09:00:00Z'
  )
ON CONFLICT(id) DO UPDATE SET
  workspace = excluded.workspace,
  source = excluded.source,
  source_id = excluded.source_id,
  state = excluded.state,
  title = excluded.title,
  detail = excluded.detail,
  body = excluded.body,
  links_json = excluded.links_json,
  tone = excluded.tone,
  sort_order = excluded.sort_order,
  is_public = excluded.is_public,
  url = excluded.url,
  updated_at = excluded.updated_at;
